data:
  images_dir: D:\ai intro\AI intro\7. Retele Complet Convolutionale\Date radiografii pulmonare - Copy\train\imagini
  right_masks_dir: D:\ai intro\AI intro\7. Retele Complet Convolutionale\Date radiografii pulmonare - Copy\train\segmentari\plamanul drept
  left_masks_dir: D:\ai intro\AI intro\7. Retele Complet Convolutionale\Date radiografii pulmonare - Copy\train\segmentari\plamanul stang
  data_csv: dataset_seg.csv

  img_size: [128,128]
  split_per:
    train: 0.7
    valid: 0.2
    test: 0.1

train:
  bs: 8
  lr: 0.0001
  opt: Adam
  epochs: 50

test:
  threshold: 0.5

augumentare:
  rotatie: 360
  factor: 2
  probabilitate: 80